"""add_facts_and_entities

Revision ID: 66ea9fe97ae0
Revises: 8fb23a18ce6e
Create Date: 2026-07-10 20:53:55.959698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ea9fe97ae0'
down_revision: Union[str, Sequence[str], None] = '8fb23a18ce6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_tag', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_registry_canonical_tag'), 'entity_registry', ['canonical_tag'], unique=True)
    op.create_index(op.f('ix_entity_registry_entity_type'), 'entity_registry', ['entity_type'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('canonical_tag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_tag'], ['entity_registry.canonical_tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_alias'), 'entity_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_entity_aliases_canonical_tag'), 'entity_aliases', ['canonical_tag'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_tag', sa.String(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object_tag', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('source_doc_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_object_tag'), 'facts', ['object_tag'], unique=False)
    op.create_index(op.f('ix_facts_predicate'), 'facts', ['predicate'], unique=False)
    op.create_index(op.f('ix_facts_status'), 'facts', ['status'], unique=False)
    op.create_index(op.f('ix_facts_subject_tag'), 'facts', ['subject_tag'], unique=False)
    op.add_column('documents', sa.Column('graph_time_ms', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('graph_built_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'graph_built_at')
    op.drop_column('documents', 'graph_time_ms')
    op.drop_index(op.f('ix_facts_subject_tag'), table_name='facts')
    op.drop_index(op.f('ix_facts_status'), table_name='facts')
    op.drop_index(op.f('ix_facts_predicate'), table_name='facts')
    op.drop_index(op.f('ix_facts_object_tag'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_entity_aliases_canonical_tag'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_entity_registry_entity_type'), table_name='entity_registry')
    op.drop_index(op.f('ix_entity_registry_canonical_tag'), table_name='entity_registry')
    op.drop_table('entity_registry')
    # ### end Alembic commands ###
