"""Add embedding and chunk columns

Revision ID: 8fb23a18ce6e
Revises: d41875653324
Create Date: 2026-07-07 23:43:41.379736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb23a18ce6e'
down_revision: Union[str, Sequence[str], None] = 'd41875653324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('embedding_time_ms', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedded_at')
    op.drop_column('documents', 'embedding_time_ms')
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'chunk_count')
    # ### end Alembic commands ###
