"""Add parsed output columns

Revision ID: d41875653324
Revises: e0fc3d60a486
Create Date: 2026-07-07 21:47:22.501206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41875653324'
down_revision: Union[str, Sequence[str], None] = 'e0fc3d60a486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_text_path', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'parsed_text_path')
    # ### end Alembic commands ###
